# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max Kooh
email: maxkooh@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  I'm an engineering student with a passion for manufacturing, systems, and design.  Not only that, I decided to develop software on the side!
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.maxkooh.com" # the base hostname & protocol for your site
github_username:  mkooh
linkedin_username: maxkooh

# Build settings
markdown: kramdown
